### ISSUE TITLE
Coffea-hats @ coffea-casa UNL todo list

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#130]
HATS sessions:

https://indico.cern.ch/event/1042860/
https://indico.cern.ch/event/1042826/

- [x] Make sure we can run on dedicated nodes (@clundst )
- [x] Test tutorials before training (@kenbloom )
- [x] Update image with `vector` (@oshadura )
- [x] Changes in CoffeaCasaCluster class
- [x] setup condor fairshare (@bbockelm @clundst  @jthiltges)
- [x] Add coffea-hats tag to image list choice
- [x] get tutorials from @lgray and @nsmith- early enough
- [x] update version of xcache (@jthiltges )
- [x] set maximum number of workers to 20

cc: @lgray @nsmith-

**Comment by nsmith-** [comment]
Can the next image also have `"hist>=2.3.0" "mplhep>=0.3.8"`?

**Comment by oshadura** [comment]
> Can the next image also have `"hist>=2.3.0" "mplhep>=0.3.8"`?

@nsmith- done, if you will restart a JH notebook server you will get requested packages.

**Comment by oshadura** [comment]
@bbockelm @clundst @jthiltges requested changes for condor fairshare are already deployed in the recent image https://github.com/CoffeaTeam/coffea-casa/blob/2021.05.06post9/coffea_casa/coffea_casa.py#L189

**Comment by clundst** [comment]
I believe I've pulled the last road blocks out for the dedicated node usage.  Not sure how to test at Scale.  Next I will add in 3 extra condor hosts.

**Comment by clundst** [comment]
It appears 2021.05.06post12 has the fairshare correct:

cms.other.coffea                          0.50 ByQuota                1000.00    258         9.01      <now>         52          
  clundstedt_unl_edu@unl.edu                                 513.42   1000.00    238         0.24      <now>                     
  tuong_phung_cern_ch@unl.edu                                524.74   1000.00      2         0.58      <now>                     
  kenbloom_unl_edu@unl.edu                                   958.43   1000.00     18         8.19      <now>

**Comment by oshadura** [comment]
@nsmith- docs were also updated: https://coffea-casa.readthedocs.io/en/latest/cc_user.html

**Comment by oshadura** [comment]
😄  everything went well!
